spring:
  application:
    name: ecommerce-backend

  data:
    mongodb:
      uri: mongodb://localhost:27017/ecommerce_db?authSource=admin

server:
  port: 3000

logging:
  level:
    org.springframework.data.mongodb: DEBUG
    com.ec.ecommerce_backend: DEBUG